"""create_customers_table

Revision ID: 55122e112627
Revises: 007
Create Date: 2025-09-04 21:23:07.578462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55122e112627'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    # ### end Alembic commands ###
