"""add staff table

Revision ID: add_staff_table
Revises: 3ffeb2a5ef85
Create Date: 2025-01-27 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_staff_table'
down_revision: Union[str, None] = '3ffeb2a5ef85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('middlename', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('employee_number', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('date_employed', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_email_address'), 'staff', ['email_address'], unique=False)
    op.create_index(op.f('ix_staff_employee_number'), 'staff', ['employee_number'], unique=True)
    op.create_index(op.f('ix_staff_firstname'), 'staff', ['firstname'], unique=False)
    op.create_index(op.f('ix_staff_lastname'), 'staff', ['lastname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_lastname'), table_name='staff')
    op.drop_index(op.f('ix_staff_firstname'), table_name='staff')
    op.drop_index(op.f('ix_staff_employee_number'), table_name='staff')
    op.drop_index(op.f('ix_staff_email_address'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
